/*
 * Copyright (c) 2022 <qb4.dev@gmail.com>
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#ifndef ESP_SUPLA_UTILS_H_
#define ESP_SUPLA_UTILS_H_

#include <libsupla/device.h>
#include <tcpip_adapter.h>
#include <esp_http_server.h>
#include <esp_err.h>

/**
 * @brief Initialize SUPLA config in NVS memory
 *
 * @param[in] supla_conf SUPLA connection config
 * @return ESP_OK on success
 */
esp_err_t supla_esp_nvs_config_init(struct supla_config *supla_conf);

/**
 * @brief Erase SUPLA config from NVS memory
 *
 * @return ESP_OK on success
 */
esp_err_t supla_esp_nvs_config_erase(void);


//TODO documentation
esp_err_t supla_config_httpd_handler(httpd_req_t *req);

/**
 * @brief generate SUPLA device hostname from device name and last two bytes
 * of MAC address like DEVNAME-XXXX

 * @param[in] dev SUPLA device instance
 * @param[out] buf output buffer
 * @param[out] len buffer length
 * @return
 *     - ESP_OK success
 *     - ESP_ERR_INVALID_ARG  no SUPLA device
 *     - ESP_ERR_INVALID_SIZE not enough space in buffer
 */
esp_err_t supla_esp_generate_hostname(supla_dev_t *dev, char* buf, size_t len);

/**
 * @brief set SUPLA device hostname generated by supla_esp_generate_hostname() function
 * on selected tcpip adapter
 *
 * @note This function must be called after esp_wifi_start() and before esp_wifi_connect()
 * selected adapter must be activated by esp_wifi_set_mode()
 *
 * @param[in] dev SUPLA device instance
 * @param[in] tcpip_if selected adapter interface
 * @return
 *     - ESP_OK success
 *     - ESP_ERR_INVALID_ARG  no SUPLA device
 *     - ESP_ERR_INVALID_SIZE not enough space in buffer
 *     - ESP_ERR_TCPIP_ADAPTER_IF_NOT_READY interface status error
 *     - ESP_ERR_TCPIP_ADAPTER_INVALID_PARAMS parameter error
 */
esp_err_t supla_esp_set_hostname(supla_dev_t *dev, tcpip_adapter_if_t tcpip_if);

/**
 * @brief init mdns with SUPLA device hostname generated by
 * supla_esp_generate_hostname() function
 *
 * @param[in] dev SUPLA device instance
 * @return
 *     - ESP_OK success
 *     - ESP_ERR_INVALID_ARG  no SUPLA device
 *     - ESP_ERR_INVALID_SIZE not enough space in buffer
 *     - ESP_ERR_INVALID_ARG Parameter error
 *     - ESP_ERR_NO_MEM memory error
 */
esp_err_t supla_esp_init_mdns(supla_dev_t *dev);


//TODO httpd config handlers GET/POST

/**
 * @brief fill SUPLA channel state with wifi connection data
 * This function should be used by
 * supla_dev_set_common_channel_state_callback()
 *
 * @param[in] dev SUPLA device instance
 * @param[out] state common channel state
 * @return 0 on success
 */
int supla_esp_get_wifi_state(supla_dev_t *dev, TDSC_ChannelState *state);

/**
 * @brief set system time from SUPLA server
 * This function should be used by
 * supla_dev_set_server_time_sync_callback()
 *
 * @param[in] dev SUPLA device instance
 * @param[in] lt SUPLA server local time
 * @return settimeofday() result
 */
int supla_esp_server_time_sync(supla_dev_t *dev, TSDC_UserLocalTimeResult *lt);


//TODO start wifi_AP with devce name+mac

#endif /* ESP_SUPLA_UTILS_H_ */
